platform :ios, '18.4'

require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

target 'mprop' do
  config = use_native_modules!

  use_react_native!(
    :path => "../node_modules/react-native",
    :hermes_enabled => true
  )

  # Add other pods here if needed
end
